baseURL = "http://nonlinear.nyc/"
languageCode = "en-us"            # idioma padrão
title = "Nonlinear"
publishDir = "docs"

[params]
author = "Nicholas Frota"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
